// Generated by `pnpm db:types` (Phase 2). Placeholder until the schema exists.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: "customer" | "shop_owner" | "admin";
    };
    CompositeTypes: Record<string, never>;
  };
};
